name: LSFDNet
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.9.24=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - mpi=1.0=mpich
  - mpi4py=3.1.4=py39hfc96bbd_0
  - mpich=3.3.2=hc856adb_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - asttokens==3.0.0
      - attrs==25.3.0
      - blinker==1.9.0
      - blobfile==3.0.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.7
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - dash==3.2.0
      - decorator==5.2.1
      - docker-pycreds==0.4.0
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.16.1
      - flask==3.1.2
      - fonttools==4.54.1
      - fsspec==2024.10.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - grpcio==1.67.1
      - h5py==3.13.0
      - huggingface-hub==0.29.1
      - idna==3.10
      - imageio==2.36.0
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipython==8.18.1
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.15
      - keras==3.9.1
      - kiwisolver==1.4.7
      - kornia==0.7.4
      - kornia-rs==0.1.7
      - lazy-loader==0.4
      - lmdb==1.5.1
      - lxml==5.3.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - namex==0.0.8
      - narwhals==2.5.0
      - natsort==8.4.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - numpy==2.0.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - open3d==0.19.0
      - opencv-python==4.10.0.84
      - openpyxl==3.1.5
      - optree==0.14.1
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.6
      - plotly==6.3.0
      - prompt-toolkit==3.0.52
      - protobuf==5.28.3
      - psutil==6.1.0
      - ptflops==0.7.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycocotools==2.0.8
      - pycryptodomex==3.21.0
      - pygments==2.19.1
      - pyparsing==3.2.0
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.3
      - retrying==1.4.2
      - rich==13.9.4
      - rpds-py==0.27.1
      - safetensors==0.5.2
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - sentry-sdk==2.18.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - stack-data==0.6.3
      - sympy==1.14.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - timm==1.0.15
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.0
      - traitlets==5.14.3
      - triton==3.4.0
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - urllib3==2.2.3
      - wandb==0.18.7
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - xformers==0.0.32.post2
      - zipp==3.21.0
prefix: /home/gyy/.conda/envs/LSFDNet
